services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - ./data:/config
      - /mnt/media:/mnt/media
      - /mnt/downdisk01:/mnt/downdisk01

    ports:
      - 8787:8787
    restart: unless-stopped
